{% set python_min = "3.10" %}
{% set name = "mudata" %}
{% set version = "0.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mudata-{{ version }}.tar.gz
  sha256: 20e518b8acbca8aa44f4318b5695ad1fae54010ac9f5899c82506b056cc2fdf1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - scipy
    - scverse-misc >=0.0.3
    - anndata >=0.10.8
    - h5py
    - numpy
    - pandas >=1.4
    - python >={{ python_min }}
    - session-info2

test:
  imports:
    - mudata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scverse/mudata
  summary: Multimodal annotated datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ilia-kats
    - ilan-gold
    - flying-sheep
    - ivirshup
    - grst
    - gtca
