{% set python_min = "3.10" %}
{% set name = "mudata" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mudata-{{ version }}.tar.gz
  sha256: c9b24f2429f369512f38e48599e341e7684abcf769df277e473700d4f1212740

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - flit-core
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - anndata >=0.10.8
    - h5py
    - numpy
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - mudata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scverse/mudata
  summary: Multimodal annotated datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ilan-gold
    - flying-sheep
    - ivirshup
    - grst
    - gtca
