{% set name = "mudata" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mudata-{{ version }}.tar.gz
  sha256: 452f166861539c118e99c432725fc6ced6064d96d333413a306cb5b04992b963

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.10
    - hatchling
    - hatch-vcs
  run:
    - anndata >=0.10.8
    - h5py
    - numpy
    - pandas
    - python >=3.10

test:
  imports:
    - mudata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scverse/mudata
  summary: Multimodal annotated datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivirshup
    - grst
    - gtca
