{% set name = "mudata" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mudata-{{ version }}.tar.gz
  sha256: 57acfd7648337840b3dc3d12a561b5364cef24fe79d5f4b539b916a7c0e029a7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core
    - pip
    - python >=3.10
    - hatchling
    - hatch-vcs
  run:
    - anndata >=0.10.8,<0.10.9
    - h5py
    - numpy
    - pandas
    - python >=3.10

test:
  imports:
    - mudata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scverse/mudata
  summary: Multimodal annotated datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivirshup
    - grst
    - gtca
